version: "3.8"

services:
  apache-web-server:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src/frontend/:/var/www/html/
    ports:
      - "80:80"
    networks:
      - my-network

  node:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=easyroomteam
      - DB_PASSWORD=1234
      - DB_NAME=easyroom
    networks:
      - my-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: easyroom
      MYSQL_USER: easyroomteam
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./easyroom-docker.sql:/docker-entrypoint-initdb.d/easyroom.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
